# Generated by Django 5.2.5 on 2025-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_alter_flight_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="type",
            field=models.CharField(
                choices=[("Nacional", "Nacional"), ("Internacional", "Internacional")],
                max_length=20,
            ),
        ),
    ]
