name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}   # o DOCKERHUB_TOKEN si así lo llamaste
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build the Docker image
        run: |
          docker build randomquotes \
            --file Tutorial #6/Dockerfile \
            --tag mlgdaniel/trabajo_topicos_ingenieria_software:latest

      - name: Push Docker image
        run: |
          docker push mlgdaniel/trabajo_topicos_ingenieria_software:latest
